---
title: "EGDS Lab Presentation"
subtitle: "F32 Submission"
author: "Andrew Dismukes"
institute: "Penn State"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [fc, fc-fonts]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: true
---

background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/be/Sharingan_triple.svg)

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

???

---
class: center, middle

## Introduction



---
class: inverse, center

## Goals
- General Feedback
- Grantsmanship
- Specific feedback on critical sections
---

### Background & Signifigance
- The *overall objective* of the proposed research is to examine the role of internalizing symptoms across childhood and into adolescence in the development of SU.
---

### Specific Aims

To test the association between longitudinal trajectories of internalizing symptoms and SU in adolescence. 

**Hypothesis 1: Elevated internalizing symptoms across childhood will be associated with elevated SU in adolescence.**
---

### Specific Aims
To test for sex differences in the relationship between SU and internalizing symptoms across early childhood and puberty. 

**Hypothesis 2: The association between internalizing symptoms and SU will be stronger in females than males.**
---

### Specific Aims
 To test the relationship between birth parent and adoptive parent contributions to the relationship between SU and internalizing symptoms across early childhood and puberty. 
 
 **Hypothesis 3a: Elevated birth parent SU will predict increased SU in adolescence and that higher levels of birth parent internalizing symptoms will be associated with higher levels of child internalizing symptoms in adolescence. Hypothesis 3b: Early parenting practices will moderate heritable influences on childhood internalizing symptoms to increase risk for adolescent SU.**
---
### Training Plan 
--